### ISSUE TITLE
realFetch.call is not a function

### ISSUE THREAD

**Issue by bazaglia** [prismagraphql/http-link-dataloader#11]
This is actually the same as related in [prismagraphql/graphql-request#85](https://github.com/prismagraphql/graphql-request/issues/85).

Someone needs to rebuild this lib so it uses an updated version of `cross-fetch` which fixes this error.

**Comment by divyenduz** [comment]
@bazaglia : How can I reproduce this error?

**Comment by bazaglia** [comment]
@divyenduz saw you open a PR already. ;)

**Comment by divyenduz** [comment]
This is released in 0.1.4 🎉
